cars = [
    { model: "brioso3", label: "Brioso 300", price: 9000, onStock: 1, category: 1 },
    { model: "weevil", label: "Weevil", price: 9000, onStock: 1, category: 1 },
    { model: "kanjo", label: "Kanjo", price: 10200, onStock: 1, category: 1 },
    { model: "issi2", label: "Issi", price: 9000, onStock: 1, category: 1 },
    { model: "previon", label: "Previon", price: 11000, onStock: 1, category: 0 },
    { model: "windsor2", label: "Windsor drop", price: 18000, onStock: 1, category: 0 },
    { model: "exemplar", label: "Exemplar", price: 22000, onStock: 1, category: 0 },
    { model: "sentinel", label: "Sentinel", price: 23000, onStock: 1, category: 0 },
    { model: "kanjosj", label: "Kanjo sj", price: 25000, onStock: 1, category: 0 },
    //{ model: "eudora", label: "Eudora", price: 12000, onStock: 1, category: 3 },
    //{ model: "vigero3", label: "Vigero ZX", price: 50000, onStock: 1, category: 3 },
    { model: "dominator8", label: "Dominator GTT", price: 30000, onStock: 1, category: 3 },
    //{ model: "dominator9", label: "Dominator GT", price: 923000, onStock: 1, category: 3 },
    { model: "dominator7", label: "Dominator ASP", price: 35000, onStock: 1, category: 3 },
    //{ model: "gauntlet5", label: "Gauntlet Classic", price: 16000, onStock: 1, category: 3 },
    { model: "yosemite", label: "Yosemite", price: 33000, onStock: 1, category: 3 },
    { model: "virgo2", label: "Virgo Custom", price: 29000, onStock: 1, category: 3 },
    { model: "chino2", label: "Chino Deluxe", price: 29000, onStock: 1, category: 3 },
    //{ model: "peyote3", label: "Peyote Custom", price: 9300, onStock: 1, category: 3 },
    //{ model: "gauntlet4", label: "Helfire", price: 23000, onStock: 1, category: 3 },
    { model: "primo2", label: "Primo Custom", price: 9000, onStock: 1, category: 7 },
    { model: "cinquemila", label: "Cinquemila", price: 24000, onStock: 1, category: 7 },
    { model: "impaler6", label: "Impaler LX", price: 923000, onStock: 1, category: 7 },
    { model: "vivanite", label: "Vivanite", price: 923000, onStock: 1, category: 6 },
    //{ model: "issi8", label: "Issi Rally", price: 9000, onStock: 1, category: 6 },
    { model: "astron", label: "Astron Custom", price: 19000, onStock: 1, category: 6 },
    { model: "baller7", label: "Baller ST", price: 20000, onStock: 1, category: 6 },
    { model: "contender", label: "Contender", price: 13000, onStock: 1, category: 6 },
    //{ model: "dubsta2", label: "Dubsta", price: 14000, onStock: 1, category: 6 },
    //{ model: "terminus", label: "Terminus", price: 923000, onStock: 1, category: 4 },
    //{ model: "monstrociti", label: "MonstroCiti", price: 6000, onStock: 1, category: 4 },
    { model: "l35", label: "Walton L35", price: 23000, onStock: 1, category: 4 },
    //{ model: "yosemite3", label: "Yosemite Ranch", price: 23000, onStock: 1, category: 4 },
    { model: "caracara2", label: "caracara 4x4", price: 30000, onStock: 1, category: 4 },
    //{ model: "outlaw", label: "Outlaw", price: 45000, onStock: 1, category: 4 },
   // { model: "kamacho", label: "Kamacho", price: 33000, onStock: 1, category: 4 },
    { model: "Kalahari", label: "Kalahari", price: 1000, onStock: 1, category: 4 },
    { model: "minivan2", label: "Minivan Custom", price: 3000, onStock: 1, category: 11 },
    { model: "youga3", label: "Youga 4x4", price: 7000, onStock: 1, category: 11 },
    { model: "speedo5", label: "Speedo", price: 8600, onStock: 1, category: 11 },
    { model: "surfer3", label: "surfer", price: 3000, onStock: 1, category: 11 },
    //{ model: "italigto", label: "Itali GTO", price: 60000, onStock: 1, category: 8 },
    //{ model: "panthere", label: "Panthere", price: 30000, onStock: 1, category: 8 },
    { model: "r300", label: "300r", price: 30000, onStock: 1, category: 8 },
    //{ model: "sentinel4", label: "Sentinel Widebody", price: 23000, onStock: 1, category: 8 },
    { model: "tenf2", label: "10F widebody", price: 63000, onStock: 1, category: 8 },
    //{ model: "omnisegt", label: "omnis GT", price: 50000, onStock: 1, category: 8 },
    //{ model: "corsita", label: "Corsita", price: 63000, onStock: 1, category: 8 },
    { model: "sultanrs", label: "Sultan RS", price: 40000, onStock: 1, category: 8 },
    //{ model: "comet3", label: "Comet Retro", price: 45000, onStock: 1, category: 8 },
    //{ model: "cypher", label: "Cypher", price: 30000, onStock: 1, category: 8 },
    //{ model: "comet6", label: "Comet S2", price: 63000, onStock: 1, category: 8 },
    //{ model: "comet7", label: "Comet S2 Cabrio", price: 73000, onStock: 1, category: 8 },
    { model: "vectre", label: "Vectre", price: 33000, onStock: 1, category: 8 },
    //{ model: "ZR350", label: "ZR350", price: 23000, onStock: 1, category: 8 },
    { model: "Rt3000", label: "Rt3000", price: 13000, onStock: 1, category: 8 },
    { model: "Euros", label: "Euros", price: 19000, onStock: 1, category: 8 },
    { model: "Growler", label: "Growler", price: 923000, onStock: 1, category: 8 },
    //{ model: "calico", label: "Calico GTF", price: 20000, onStock: 1, category: 8 },
    //{ model: "italirsx", label: "Itali RSX", price: 90000, onStock: 1, category: 8 },
    //{ model: "penumbra2", label: "Penumbra FF", price: 33000, onStock: 1, category: 8 },
    { model: "coquette4", label: "Coquette D10", price: 80000, onStock: 1, category: 8 },
    { model: "sugoi", label: "Sugoi", price: 23000, onStock: 1, category: 8 },
    { model: "komoda", label: "Komoda", price: 25000, onStock: 1, category: 8 },
    //{ model: "sultan2", label: "Sultan", price: 33000, onStock: 1, category: 8 },
    { model: "Jugular", label: "Jugular", price: 50000, onStock: 1, category: 8 },
    //{ model: "Neo", label: "Neo", price: 30000, onStock: 1, category: 8 },
    { model: "Neon", label: "Neon", price: 120000, onStock: 1, category: 8 },
    { model: "Kuruma", label: "Kuruma", price: 23000, onStock: 1, category: 8 },
    { model: "Feltzer2", label: "Feltzer", price: 12000, onStock: 1, category: 8 },
    { model: "elegy2", label: "Elegy RH8", price: 15000, onStock: 1, category: 8 },
    //{ model: "elegy", label: "Elegy", price: 40000, onStock: 1, category: 8 },
    //{ model: "turismo3", label: "Turismo Omaggio", price: 923000, onStock: 1, category: 9 },
    { model: "Virtue", label: "Virtue", price: 120000, onStock: 1, category: 9 },
    { model: "entity2", label: "Entity MT", price: 92000, onStock: 1, category: 9 },
    //{ model: "torero2", label: "Torero XO", price: 300000, onStock: 1, category: 9 },
    //{ model: "Ignus", label: "Ignus", price: 150000, onStock: 1, category: 9 },
    { model: "Cyclone", label: "Cyclone ", price: 120000, onStock: 1, category: 9 },
    //{ model: "Zeno", label: "Zeno", price: 180000, onStock: 1, category: 9 },
    { model: "Champion", label: "Champion", price: 70000, onStock: 1, category: 9 },
    //{ model: "Furia", label: "Furia", price: 90000, onStock: 1, category: 9 },
    //{ model: "Zorrusso", label: "Zorrusso", price: 123000, onStock: 1, category: 9 },
    //{ model: "Emerus", label: "Emerus", price: 300000, onStock: 1, category: 9 },
    { model: "Thrax", label: "Thrax", price: 250000, onStock: 1, category: 9 },
    //{ model: "Tyrant", label: "Tyrant", price: 123000, onStock: 1, category: 9 },
    //{ model: "EntityXF", label: "Entity XF", price: 180000, onStock: 1, category: 9 },
    //{ model: "Visione", label: "Visione", price: 150000, onStock: 1, category: 9 },
    { model: "Xa21", label: "Xa-21", price: 230000, onStock: 1, category: 9 },
    //{ model: "vagner", label: "Vagner", price: 150000, onStock: 1, category: 9 },
    //{ model: "italigtb2", label: "itali GTB", price: 150000, onStock: 1, category: 9 },
    { model: "Tempesta", label: "Tempesta", price: 190000, onStock: 1, category: 9 },
    //{ model: "Reaper", label: "Reaper", price: 923000, onStock: 1, category: 9 },
    { model: "T20", label: "T20", price: 923000, onStock: 1, category: 9 },
    { model: "zentorno", label: "Zentorno", price: 923000, onStock: 1, category: 9 },
    { model: "TurismoR", label: "TurismoR", price: 923000, onStock: 1, category: 9 },
    { model: "Vacca", label: "Vacca", price: 923000, onStock: 1, category: 9 },
    { model: "Cheetah", label: "Cheetah", price: 923000, onStock: 1, category: 9 },
    //{ model: "Reever", label: "Reever", price: 923000, onStock: 1, category: 2 },
    //{ model: "shinobi", label: "Shinobi", price: 923000, onStock: 1, category: 2 },
    { model: "Vortex", label: "Vortex", price: 923000, onStock: 1, category: 2 },
    { model: "Daemon", label: "Daemon", price: 923000, onStock: 1, category: 2 },
    { model: "faggio2", label: "Faggio", price: 923000, onStock: 1, category: 2 },
    //{ model: "diabolus2", label: "Diabolus Custom", price: 923000, onStock: 1, category: 2 },
    //{ model: "nightblade", label: "NightBlade", price: 923000, onStock: 1, category: 2 },
    { model: "Hakuchou", label: "Hakuchou", price: 923000, onStock: 1, category: 2 },
    { model: "BF400", label: "BF400", price: 923000, onStock: 1, category: 2 },
    { model: "Sanches2", label: "Sanches2", price: 900, onStock: 1, category: 2 },
    //{ model: "vindicator", label: "Vindicator", price: 923000, onStock: 1, category: 2 },
    { model: "double", label: "Double-T", price: 923000, onStock: 1, category: 2 },
    //{ model: "carbonrs", label: "Carbon RS", price: 923000, onStock: 1, category: 2 },
    { model: "bati", label: "Bati801", price: 900, onStock: 1, category: 2 },
   
]