Config = Config or {}

Config.Vehicles = {
    ['brioso2'] = {
        ['name'] = 'Brioso 300',
        ['brand'] = 'Iniciacion',
        ['model'] = 'brioso2',
        ['price'] = 0,
        ['category'] = 'compacts',
        ['hash'] = `brioso2`,
        ['shop'] = 'pdm',
    },
    ['faggio'] = {
        ['name'] = 'Faggio Sport',
        ['brand'] = 'Iniciacion',
        ['model'] = 'faggio',
        ['price'] = 0,
        ['category'] = 'motorcycles',
        ['hash'] = `faggio`,
        ['shop'] = 'pdm',
    },
    --- Compacts

    ['club'] = {
        ['name'] = 'Club',
        ['brand'] = 'compacts',
        ['model'] = 'club',
        ['price'] = 0,
        ['category'] = 'compacts',
        ['hash'] = `club`,
        ['shop'] = 'pdm',
    },
    ['asbo'] = {
        ['name'] = 'Asbo',
        ['brand'] = 'compacts',
        ['model'] = 'asbo',
        ['price'] = 0,
        ['category'] = 'compacts',
        ['hash'] = `asbo`,
        ['shop'] = 'pdm',
    },
    ['kanjo'] = {
        ['name'] = 'Blista Kanjo',
        ['brand'] = 'compacts',
        ['model'] = 'kanjo',
        ['price'] = 0,
        ['category'] = 'compacts',
        ['hash'] = `kanjo`,
        ['shop'] = 'pdm',
    },
    ['blista'] = {
        ['name'] = 'Blista',
        ['brand'] = 'compacts',
        ['model'] = 'blista',
        ['price'] = 0,
        ['category'] = 'compacts',
        ['hash'] = `blista`,
        ['shop'] = 'pdm',
    },
    ['weevil'] = {
        ['name'] = 'Weevil',
        ['brand'] = 'compacts',
        ['model'] = 'weevil',
        ['price'] = 0,
        ['category'] = 'compacts',
        ['hash'] = `weevil`,
        ['shop'] = 'pdm',
    },



    --- Coupes
    ['cogcabrio'] = {
        ['name'] = 'Cognoscenti Cabrio', -- 2 puertas
        ['brand'] = 'coupes',
        ['model'] = 'cogcabrio',--175 kph
        ['price'] = 0,
        ['category'] = 'coupes',
        ['hash'] = `cogcabrio`,
        ['shop'] = 'pdm',
    },
    ['exemplar'] = {
        ['name'] = 'Exemplar',-- 4 puertas
        ['brand'] = 'coupes',
        ['model'] = 'exemplar', --182 kph
        ['price'] = 0,
        ['category'] = 'coupes',
        ['hash'] = `exemplar`,
        ['shop'] = 'pdm',
    },
    ['f620'] = {
        ['name'] = 'F620', -- 2 puertas
        ['brand'] = 'coupes',
        ['model'] = 'f620', -- 195 kph
        ['price'] = 0,
        ['category'] = 'coupes',
        ['hash'] = `f620`,
        ['shop'] = 'pdm',
    },
    ['felon'] = {
        ['name'] = 'Felon', -- 4 puertas
        ['brand'] = 'coupes',
        ['model'] = 'felon', -- 175 kph
        ['price'] = 0,
        ['category'] = 'coupes',
        ['hash'] = `felon`,
        ['shop'] = 'pdm',
    },
    ['felon2'] = {
        ['name'] = 'Felon GT', -- 2 puertas
        ['brand'] = 'coupes',
        ['model'] = 'felon2', -- 175 kph
        ['price'] = 0,
        ['category'] = 'coupes',
        ['hash'] = `felon2`,
        ['shop'] = 'pdm',
    },
    ['jackal'] = {
        ['name'] = 'Jackal', -- 4 puertas
        ['brand'] = 'coupes',
        ['model'] = 'jackal', -- 180 kph
        ['price'] = 0,
        ['category'] = 'coupes',
        ['hash'] = `jackal`,
        ['shop'] = 'pdm',
    },
    ['oracle'] = {
        ['name'] = 'Oracle', -- 4 puertas
        ['brand'] = 'coupes',
        ['model'] = 'oracle', -- 180 kph
        ['price'] = 0,
        ['category'] = 'sedans',
        ['hash'] = `oracle`,
        ['shop'] = 'pdm',
    },
    ['oracle2'] = {
        ['name'] = 'Oracle XS', -- 4 puertas
        ['brand'] = 'coupes',
        ['model'] = 'oracle2', -- 180 kph
        ['price'] = 0,
        ['category'] = 'coupes',
        ['hash'] = `oracle2`,
        ['shop'] = 'pdm',
    },
    ['sentinel'] = {
        ['name'] = 'Sentinel', -- 2 puertas
        ['brand'] = 'coupes',
        ['model'] = 'sentinel',	-- 165 kph
        ['price'] = 0,
        ['category'] = 'coupes',
        ['hash'] = `sentinel`,
        ['shop'] = 'pdm',
    },
    ['sentinel2'] = {
        ['name'] = 'Sentinel XS', -- 2 puertas
        ['brand'] = 'coupes',
        ['model'] = 'sentinel2', -- 180 kph
        ['price'] = 0,
        ['category'] = 'coupes',
        ['hash'] = `sentinel2`,
        ['shop'] = 'pdm',
    },
    ['windsor'] = {
        ['name'] = 'Windsor', -- 2 puertas
        ['brand'] = 'coupes',
        ['model'] = 'windsor', -- 190 kph
        ['price'] = 0,
        ['category'] = 'coupes',
        ['hash'] = `windsor`,
        ['shop'] = 'pdm',
    },
    ['windsor2'] = {
        ['name'] = 'Windsor Drop',	-- 4 puertas
        ['brand'] = 'coupes',
        ['model'] = 'windsor2', -- 190 kph
        ['price'] = 0,
        ['category'] = 'coupes',
        ['hash'] = `windsor2`,
        ['shop'] = 'pdm',
    },
    ['zion'] = {
        ['name'] = 'Zion', -- 2 puertas
        ['brand'] = 'coupes',
        ['model'] = 'zion', -- 180 kph
        ['price'] = 0,
        ['category'] = 'coupes',
        ['hash'] = `zion`,
        ['shop'] = 'pdm',
    },
    ['zion2'] = {
        ['name'] = 'Zion Cabrio', -- 2 puertas
        ['brand'] = 'coupes',
        ['model'] = 'zion2', -- 180 kph
        ['price'] = 0,
        ['category'] = 'coupes',
        ['hash'] = `zion2`,
        ['shop'] = 'pdm',
    },
    ['previon'] = {			--DLC +set sv_enforceGameBuild 2372
        ['name'] = 'Previon', -- 2 puertas
        ['brand'] = 'coupes',
        ['model'] = 'previon', -- 180 kph
        ['price'] = 0,
        ['category'] = 'coupes',
        ['hash'] = `previon`,
        ['shop'] = 'pdm',
    },
    -- fin cupes

    ['champion'] = {		--DLC +set sv_enforceGameBuild 2545
        ['name'] = 'Champion',
        ['brand'] = 'Dewbauchee',
        ['model'] = 'champion',
        ['price'] = 0,
        ['category'] = 'coupes',
        ['hash'] = `champion`,
        ['shop'] = 'pdm',
    },
    ['ignus'] = { 	 	--DLC +set sv_enforceGameBuild 2545
        ['name'] = 'Ignus',
        ['brand'] = 'Pegassi',
        ['model'] = 'ignus',
        ['price'] = 0,
        ['category'] = 'coupes',
        ['hash'] = `ignus`,
        ['shop'] = 'pdm',
    },
    ['zeno'] = { 	 	--DLC +set sv_enforceGameBuild 2545
        ['name'] = 'Zeno',
        ['brand'] = 'Overflod',
        ['model'] = 'zeno',
        ['price'] = 0,
        ['category'] = 'coupes',
        ['hash'] = `zeno`,
        ['shop'] = 'pdm',
    },
    --- Cycles
    ['bmx'] = {
        ['name'] = 'BMX',
        ['brand'] = 'Bike',
        ['model'] = 'bmx',
        ['price'] = 0,
        ['category'] = 'cycles',
        ['hash'] = `bmx`,
        ['shop'] = 'pdm',
    },
    ['cruiser'] = {
        ['name'] = 'Cruiser',
        ['brand'] = 'Bike',
        ['model'] = 'cruiser',
        ['price'] = 0,
        ['category'] = 'cycles',
        ['hash'] = `cruiser`,
        ['shop'] = 'pdm',
    },
    ['fixter'] = {
        ['name'] = 'Fixter',
        ['brand'] = 'Bike',
        ['model'] = 'fixter',
        ['price'] = 0,
        ['category'] = 'cycles',
        ['hash'] = `fixter`,
        ['shop'] = 'pdm',
    },
    ['scorcher'] = {
        ['name'] = 'Scorcher',
        ['brand'] = 'Bike',
        ['model'] = 'scorcher',
        ['price'] = 0,
        ['category'] = 'cycles',
        ['hash'] = `scorcher`,
        ['shop'] = 'pdm',
    },
    ['tribike'] = {
        ['name'] = 'Tri Bike',
        ['brand'] = 'Bike',
        ['model'] = 'tribike',
        ['price'] = 0,
        ['category'] = 'cycles',
        ['hash'] = `tribike`,
        ['shop'] = 'pdm',
    },
    ['tribike2'] = {
        ['name'] = 'Tri Bike 2',
        ['brand'] = 'Bike',
        ['model'] = 'tribike2',
        ['price'] = 0,
        ['category'] = 'cycles',
        ['hash'] = `tribike2`,
        ['shop'] = 'pdm',
    },
    ['tribike3'] = {
        ['name'] = 'Tri Bike 3',
        ['brand'] = 'Bike',
        ['model'] = 'tribike3',
        ['price'] = 0,
        ['category'] = 'cycles',
        ['hash'] = `tribike3`,
        ['shop'] = 'pdm',
    },
    --- Motorcycles

    ['sanchez'] = {
        ['name'] = 'Sanchez Livery',
        ['brand'] = 'motorcycles',
        ['model'] = 'sanchez', --155 kph
        ['price'] = 0,
        ['category'] = 'motorcycles',
        ['hash'] = `sanchez`,
        ['shop'] = 'pdm',
    },
    ['bati'] = {
        ['name'] = 'Bati 801',
        ['brand'] = 'motorcycles',
        ['model'] = 'bati', -- 190 kph
        ['price'] = 0,
        ['category'] = 'motorcycles',
        ['hash'] = `bati`,
        ['shop'] = 'pdm',
    },
    ['bf400'] = {
        ['name'] = 'BF400', 
        ['brand'] = 'motorcycles',
        ['model'] = 'bf400', -- 190 kph
        ['price'] = 0,
        ['category'] = 'motorcycles',
        ['hash'] = `bf400`,
        ['shop'] = 'pdm',
    },
    ['hakuchou'] = {
        ['name'] = 'Hakuchou',
        ['brand'] = 'motorcycles',
        ['model'] = 'hakuchou', -- 190 kph
        ['price'] = 0,
        ['category'] = 'motorcycles',
        ['hash'] = `hakuchou`,
        ['shop'] = 'pdm',
    },
    ['innovation'] = {
        ['name'] = 'Innovation',
        ['brand'] = 'motorcycles',
        ['model'] = 'innovation', -- 170 kph
        ['price'] = 0,
        ['category'] = 'motorcycles',
        ['hash'] = `innovation`,
        ['shop'] = 'pdm',
    },
    ['vortex'] = {
        ['name'] = 'Vortex',
        ['brand'] = 'motorcycles',
        ['model'] = 'vortex', -- 185 kph
        ['price'] = 0,
        ['category'] = 'motorcycles',
        ['hash'] = `vortex`,
        ['shop'] = 'pdm',
    },
    ['zombieb'] = {
        ['name'] = 'Zombie Chopper',
        ['brand'] = 'motorcycles',
        ['model'] = 'zombieb', -- 170 kph
        ['price'] = 0,
        ['category'] = 'motorcycles',
        ['hash'] = `zombieb`,
        ['shop'] = 'pdm',
    },
    --- Muscle

    ['buccaneer'] = {
        ['name'] = 'Buccaneer', -- 2 puertas
        ['brand'] = 'muscle',
        ['model'] = 'buccaneer', -- 165 kph
        ['price'] = 0,
        ['category'] = 'muscle',
        ['hash'] = `buccaneer`,
        ['shop'] = 'pdm',
    },
    ['buccaneer2'] = {
        ['name'] = 'Buccaneer Rider', -- 2 puertas
        ['brand'] = 'muscle',
        ['model'] = 'buccaneer2', -- 175 kph
        ['price'] = 0,
        ['category'] = 'muscle',
        ['hash'] = `buccaneer2`,
        ['shop'] = 'pdm',
    },
    ['chino2'] = {
        ['name'] = 'Chino Luxe', -- 2 puertas
        ['brand'] = 'muscle',
        ['model'] = 'chino2', -- 175 kph
        ['price'] = 0,
        ['category'] = 'muscle',
        ['hash'] = `chino2`,
        ['shop'] = 'pdm',
    },
    ['dominator3'] = {
        ['name'] = 'Dominator GTX', -- 2 puertas
        ['brand'] = 'muscle',
        ['model'] = 'dominator3', -- 175 kph
        ['price'] = 0,
        ['category'] = 'muscle',
        ['hash'] = `dominator3`,
        ['shop'] = 'pdm',
    },
    ['ellie'] = {
        ['name'] = 'Ellie', -- 2 puertas
        ['brand'] = 'muscle',
        ['model'] = 'ellie', -- 170 kph
        ['price'] = 0,
        ['category'] = 'muscle',
        ['hash'] = `ellie`,
        ['shop'] = 'pdm',
    },
    ['impaler'] = {							--DLC
        ['name'] = 'impaler', -- 2 puertas
        ['brand'] = 'muscle',
        ['model'] = 'impaler', -- 175 kph
        ['price'] = 0,
        ['category'] = 'muscle',
        ['hash'] = `impaler`,
        ['shop'] = 'pdm',
    },
    ['yosemite'] = {
        ['name'] = 'Yosemite',
        ['brand'] = 'muscle',
        ['model'] = 'yosemite',
        ['price'] = 0,
        ['category'] = 'muscle',
        ['hash'] = `yosemite`,
        ['shop'] = 'pdm',
    },
    ['yosemite2'] = {
        ['name'] = 'Yosemite Drift',
        ['brand'] = 'muscle',
        ['model'] = 'yosemite2',
        ['price'] = 0,
        ['category'] = 'muscle',
        ['hash'] = `yosemite2`,
        ['shop'] = 'pdm',
    },
    ['yosemite3'] = {
        ['name'] = 'Yosemite Rancher',
        ['brand'] = 'offroad',
        ['price'] = 0,
        ['category'] = 'offroad',
        ['model'] = 'yosemite3',
        ['hash'] = `yosemite3`,
        ['shop'] = 'pdm',
    },
    ['buffalo4'] = { 	 	--DLC +set sv_enforceGameBuild 2545
        ['name'] = 'Buffalo STX',
        ['brand'] = 'muscle',
        ['model'] = 'buffalo4',
        ['price'] = 0,
        ['category'] = 'muscle',
        ['hash'] = `buffalo4`,
        ['shop'] = 'pdm',
    },
    --- Off-Road

    ['blazer'] = {
        ['name'] = 'Blazer',
        ['brand'] = 'offroad',
        ['price'] = 0,
        ['category'] = 'offroad',
        ['model'] = 'blazer',
        ['hash'] = `blazer`,
        ['shop'] = 'pdm',
    },
    ['caracara2'] = {							--DLC
        ['name'] = 'Caracara 4x4',
        ['brand'] = 'Vapid',
        ['model'] = 'caracara2',
        ['price'] = 0,
        ['category'] = 'offroad',
        ['hash'] = `caracara2`,
        ['shop'] = 'pdm',
    },
    ['dubsta3'] = {
        ['name'] = 'Dubsta 6x6',
        ['brand'] = 'offroad',
        ['price'] = 0,
        ['category'] = 'offroad',
        ['model'] = 'dubsta3',
        ['hash'] = `dubsta3`,
        ['shop'] = 'pdm',
    },
    ['everon'] = {
        ['name'] = 'Everon',
        ['brand'] = 'offroad',
        ['model'] = 'everon',
        ['price'] = 0,
        ['category'] = 'offroad',
        ['hash'] = `everon`,
        ['shop'] = 'pdm',
    },
    ['kamacho'] = {
        ['name'] = 'Kamacho',
        ['brand'] = 'offroad',
        ['model'] = 'kamacho',
        ['price'] = 0,
        ['category'] = 'offroad',
        ['hash'] = `kamacho`,
        ['shop'] = 'pdm',
    },
    ['mesa3'] = {
        ['name'] = 'Mesa Merryweather',
        ['brand'] = 'Canis',
        ['model'] = 'mesa3',
        ['price'] = 0,
        ['category'] = 'offroad',
        ['hash'] = `mesa3`,
        ['shop'] = 'pdm',
    },
    ['outlaw'] = {
        ['name'] = 'Outlaw',
        ['brand'] = 'offroad',
        ['model'] = 'outlaw',
        ['price'] = 0,
        ['category'] = 'offroad',
        ['hash'] = `outlaw`,
        ['shop'] = 'pdm',
    },
    ['vagrant'] = {
        ['name'] = 'Vagrant',
        ['brand'] = 'offroad',
        ['price'] = 0,
        ['category'] = 'offroad',
        ['model'] = 'vagrant',
        ['hash'] = `vagrant`,
        ['shop'] = 'pdm',
    },
    ['winky'] = {
        ['name'] = 'Winky',
        ['brand'] = 'offroad',
        ['price'] = 0,
        ['category'] = 'offroad',
        ['model'] = 'winky',
        ['hash'] = `winky`,
        ['shop'] = 'pdm',
    },
    --- SUVs

    ['baller4'] = {
        ['name'] = 'Baller LE LWB',
        ['brand'] = 'suvs',
        ['model'] = 'baller4',
        ['price'] = 0,
        ['category'] = 'suvs',
        ['hash'] = `baller4`,
        ['shop'] = 'pdm',
    },
    ['cavalcade2'] = {
        ['name'] = 'Cavalcade',
        ['brand'] = 'suvs',
        ['model'] = 'cavalcade2',
        ['price'] = 0,
        ['category'] = 'suvs',
        ['hash'] = `cavalcade2`,
        ['shop'] = 'pdm',
    },
    ['dubsta2'] = {
        ['name'] = 'Dubsta Luxuary',
        ['brand'] = 'suvs',
        ['model'] = 'dubsta2',
        ['price'] = 0,
        ['category'] = 'suvs',
        ['hash'] = `dubsta2`,
        ['shop'] = 'pdm',
    },
    ['gresley'] = {
        ['name'] = 'Gresley',
        ['brand'] = 'suvs',
        ['model'] = 'gresley',
        ['price'] = 0,
        ['category'] = 'suvs',
        ['hash'] = `gresley`,
        ['shop'] = 'pdm',
    },
    ['rebla'] = {
        ['name'] = 'Rebla GTS',
        ['brand'] = 'suvs',
        ['model'] = 'rebla',
        ['price'] = 0,
        ['category'] = 'suvs',
        ['hash'] = `rebla`,
        ['shop'] = 'pdm',
    },
    ['xls'] = {
        ['name'] = 'XLS',
        ['brand'] = 'suvs',
        ['model'] = 'xls',
        ['price'] = 0,
        ['category'] = 'suvs',
        ['hash'] = `xls`,
        ['shop'] = 'pdm',
    },
    --- Sedans

    --- Sports

    ['banshee'] = {
        ['name'] = 'Banshee',
        ['brand'] = 'sports',
        ['model'] = 'banshee',
        ['price'] = 0,
        ['category'] = 'sports',
        ['hash'] = `banshee`,
        ['shop'] = 'luxury',
    },
    ['carbonizzare'] = {
        ['name'] = 'Carbonizzare',
        ['brand'] = 'sports',
        ['model'] = 'carbonizzare',
        ['price'] = 0,
        ['category'] = 'sports',
        ['hash'] = `carbonizzare`,
        ['shop'] = 'luxury',
    },
    ['comet2'] = {
        ['name'] = 'Comet',
        ['brand'] = 'sports',
        ['model'] = 'comet2',
        ['price'] = 0,
        ['category'] = 'sports',
        ['hash'] = `comet2`,
        ['shop'] = 'luxury',
    },
    ['coquette'] = {
        ['name'] = 'Coquette',
        ['brand'] = 'sports',
        ['model'] = 'coquette',
        ['price'] = 0,
        ['category'] = 'sports',
        ['hash'] = `coquette`,
        ['shop'] = 'luxury',
    },
    ['coquette2'] = {
        ['name'] = 'Coquette Classic',
        ['brand'] = 'sports',
        ['model'] = 'coquette2',
        ['price'] = 0,
        ['category'] = 'sportsclassics',
        ['hash'] = `coquette2`,
        ['shop'] = 'pdm',
    },
    ['drafter'] = {							--DLC
        ['name'] = '8F Drafter',
        ['brand'] = 'sports',
        ['model'] = 'drafter',
        ['price'] = 0,
        ['category'] = 'sports',
        ['hash'] = `drafter`,
        ['shop'] = 'luxury',
    },
    ['elegy'] = {							--DLC
        ['name'] = 'Elegy Retro Custom',
        ['brand'] = 'sports',
        ['model'] = 'elegy',
        ['price'] = 0,
        ['category'] = 'sports',
        ['hash'] = `elegy`,
        ['shop'] = 'luxury',
    },
    ['elegy2'] = {
        ['name'] = 'Elegy RH8',
        ['brand'] = 'sports',
        ['model'] = 'elegy2',
        ['price'] = 0,
        ['category'] = 'sports',
        ['hash'] = `elegy2`,
        ['shop'] = 'luxury',
    },
    ['feltzer2'] = {
        ['name'] = 'Feltzer',
        ['brand'] = 'sports',
        ['model'] = 'feltzer2',
        ['price'] = 0,
        ['category'] = 'sports',
        ['hash'] = `feltzer2`,
        ['shop'] = 'luxury',
    },
    ['futo'] = {
        ['name'] = 'Futo',
        ['brand'] = 'sports',
        ['model'] = 'futo',
        ['price'] = 0,
        ['category'] = 'coupes',
        ['hash'] = `futo`,
        ['shop'] = 'pdm',
    },
    ['gb200'] = {
        ['name'] = 'GB 200',
        ['brand'] = 'sports',
        ['model'] = 'gb200',
        ['price'] = 0,
        ['category'] = 'sports',
        ['hash'] = `gb200`,
        ['shop'] = 'luxury',
    },
    ['komoda'] = {
        ['name'] = 'Komoda',
        ['brand'] = 'sports',
        ['model'] = 'komoda',
        ['price'] = 0,
        ['category'] = 'sports',
        ['hash'] = `komoda`,
        ['shop'] = 'luxury',
    },
    ['imorgon'] = {
        ['name'] = 'Imorgon',
        ['brand'] = 'sports',
        ['model'] = 'imorgon',
        ['price'] = 0,
        ['category'] = 'sports',
        ['hash'] = `imorgon`,
        ['shop'] = 'luxury',
    },
    ['kuruma'] = {
        ['name'] = 'Kuruma',
        ['brand'] = 'sports',
        ['model'] = 'kuruma',
        ['price'] = 0,
        ['category'] = 'sports',
        ['hash'] = `kuruma`,
        ['shop'] = 'luxury',
    },
    ['lynx'] = {
        ['name'] = 'Lynx',
        ['brand'] = 'Ocelot',
        ['model'] = 'lynx',
        ['price'] = 0,
        ['category'] = 'sports',
        ['hash'] = `lynx`,
        ['shop'] = 'luxury',
    },
    ['schafter2'] = {
        ['name'] = 'Schafter',
        ['brand'] = 'sedans',
        ['model'] = 'schafter2',
        ['price'] = 0,
        ['category'] = 'sedans',
        ['hash'] = `schafter2`,
        ['shop'] = 'pdm',
    },
    ['schlagen'] = {							--DLC
        ['name'] = 'Schlagen GT',
        ['brand'] = 'sports',
        ['model'] = 'schlagen',
        ['price'] = 0,
        ['category'] = 'sports',
        ['hash'] = `schlagen`,
        ['shop'] = 'luxury',
    },
    ['sultan'] = {
        ['name'] = 'Sultan',
        ['brand'] = 'sports',
        ['model'] = 'sultan',
        ['price'] = 0,
        ['category'] = 'sports',
        ['hash'] = `sultan`,
        ['shop'] = 'luxury',
    },
    ['italirsx'] = {
        ['name'] = 'Itali RSX',
        ['brand'] = 'sports',
        ['model'] = 'italirsx',
        ['price'] = 0,
        ['category'] = 'sports',
        ['hash'] = `italirsx`,
        ['shop'] = 'luxury',
    },
    ['zr350'] = {							--DLC +set sv_enforceGameBuild 2372
        ['name'] = 'ZR350',
        ['brand'] = 'sports',
        ['model'] = 'zr350',
        ['price'] = 0,
        ['category'] = 'sports',
        ['hash'] = `zr350`,
        ['shop'] = 'luxury',
    },
    ['futo2'] = {							--DLC +set sv_enforceGameBuild 2372
        ['name'] = 'Futo GTX',
        ['brand'] = 'sports',
        ['model'] = 'futo2',
        ['price'] = 0,
        ['category'] = 'sports',
        ['hash'] = `futo2`,
        ['shop'] = 'luxury',
    },
    ['growler'] = {							--DLC +set sv_enforceGameBuild 2372
        ['name'] = 'Growler',
        ['brand'] = 'sports',
        ['model'] = 'growler',
        ['price'] = 0,
        ['category'] = 'sports',
        ['hash'] = `growler`,
        ['shop'] = 'luxury',
    },
    ['sultan3'] = {							--DLC +set sv_enforceGameBuild 2372
        ['name'] = 'Sultan Classic Custom',
        ['brand'] = 'sports',
        ['model'] = 'sultan3',
        ['price'] = 0,
        ['category'] = 'sports',
        ['hash'] = `sultan3`,
        ['shop'] = 'luxury',
    },
    ['rt0'] = {							--DLC +set sv_enforceGameBuild 2372
        ['name'] = 'RT0',
        ['brand'] = 'sports',
        ['model'] = 'rt0',
        ['price'] = 0,
        ['category'] = 'sports',
        ['hash'] = `rt0`,
        ['shop'] = 'luxury',
    },
    --- Sports Classic

    ['casco'] = {
        ['name'] = 'Casco',
        ['brand'] = 'sports classics',
        ['model'] = 'casco',
        ['price'] = 0,
        ['category'] = 'sportsclassics',
        ['hash'] = `casco`,
        ['shop'] = 'pdm',
    },
    ['dynasty'] = {							--DLC
        ['name'] = 'Dynasty',
        ['brand'] = 'sports classics',
        ['model'] = 'dynasty',
        ['price'] = 0,
        ['category'] = 'sportsclassics',
        ['hash'] = `dynasty`,
        ['shop'] = 'dynasty',
    },
    ['zion3'] = {							--DLC
        ['name'] = 'Zion Classic',
        ['brand'] = 'sports classics',
        ['model'] = 'zion3',
        ['price'] = 0,
        ['category'] = 'sportsclassics',
        ['hash'] = `zion3`,
        ['shop'] = 'pdm',
    },
    --- Super
    ['adder'] = {
        ['name'] = 'Adder',
        ['brand'] = 'super',
        ['model'] = 'adder',
        ['price'] = 0,
        ['category'] = 'super',
        ['hash'] = `adder`,
        ['shop'] = 'luxury',
    },
    ['sultanrs'] = {
        ['name'] = 'Sultan RS',
        ['brand'] = 'sports',
        ['model'] = 'sultanrs',
        ['price'] = 0,
        ['category'] = 'sports',
        ['hash'] = `sultanrs`,
        ['shop'] = 'luxury',
    },
    ['t20'] = {
        ['name'] = 'T20',
        ['brand'] = 'super',
        ['model'] = 't20',
        ['price'] = 0,
        ['category'] = 'super',
        ['hash'] = `t20`,
        ['shop'] = 'luxury',
    },
    ['vacca'] = {
        ['name'] = 'Vacca',
        ['brand'] = 'Pegassi',
        ['model'] = 'vacca',
        ['price'] = 0,
        ['category'] = 'super',
        ['hash'] = `vacca`,
        ['shop'] = 'luxury',
    },
    ['zentorno'] = {
        ['name'] = 'Zentorno',
        ['brand'] = 'Pegassi',
        ['model'] = 'zentorno',
        ['price'] = 0,
        ['category'] = 'super',
        ['hash'] = `zentorno`,
        ['shop'] = 'luxury',
    },
    -- Vans
    ['gburrito2'] = {
        ['name'] = 'Burrito Custom',
        ['brand'] = 'Declasse',
        ['model'] = 'gburrito2',
        ['price'] = 0,
        ['category'] = 'vans',
        ['hash'] = `gburrito2`,
        ['shop'] = 'pdm',
    },
    ['minivan2'] = {
        ['name'] = 'Minivan Custom',
        ['brand'] = 'Vapid',
        ['model'] = 'minivan2',
        ['price'] = 0,
        ['category'] = 'vans',
        ['hash'] = `minivan2`,
        ['shop'] = 'pdm',
    },
    ['speedo'] = {
        ['name'] = 'Speedo',
        ['brand'] = 'Vapid',
        ['model'] = 'speedo',
        ['price'] = 0,
        ['category'] = 'vans',
        ['hash'] = `speedo`,
        ['shop'] = 'pdm',
    },
    ['surfer'] = {
        ['name'] = 'Surfer',
        ['brand'] = 'BF',
        ['model'] = 'surfer',
        ['price'] = 0,
        ['category'] = 'vans',
        ['hash'] = `surfer`,
        ['shop'] = 'pdm',
    },
    ['youga3'] = {
        ['name'] = 'Youga Classic 4x4',
        ['brand'] = 'Bravado',
        ['model'] = 'youga3',
        ['price'] = 0,
        ['category'] = 'vans',
        ['hash'] = `youga3`,
        ['shop'] = 'pdm',
    },
    -- Utility
        -- Boats
    ['squalo'] = {
        ['name'] = 'Squalo',
        ['brand'] = 'Shitzu',
        ['model'] = 'squalo',
        ['price'] = 0,
        ['category'] = 'boats',
        ['hash'] = `squalo`,
        ['shop'] = 'boats',
    },
    ['marquis'] = {
        ['name'] = 'Marquis',
        ['brand'] = 'Dinka',
        ['model'] = 'marquis',
        ['price'] = 0,
        ['category'] = 'boats',
        ['hash'] = `marquis`,
        ['shop'] = 'boats',
    },
    ['seashark'] = {
        ['name'] = 'Seashark',
        ['brand'] = 'Speedophile',
        ['model'] = 'seashark',
        ['price'] = 0,
        ['category'] = 'boats',
        ['hash'] = `seashark`,
        ['shop'] = 'boats',
    },
    ['seashark2'] = {
        ['name'] = 'Seashark',
        ['brand'] = 'Speedophile',
        ['model'] = 'seashark2',
        ['price'] = 0,
        ['category'] = 'boats',
        ['hash'] = `seashark2`,
        ['shop'] = 'boats',
    },
    ['seashark3'] = {
        ['name'] = 'Seashark',
        ['brand'] = 'Speedophile',
        ['model'] = 'seashark3',
        ['price'] = 0,
        ['category'] = 'boats',
        ['hash'] = `seashark3`,
        ['shop'] = 'boats',
    },
    ['jetmax'] = {
        ['name'] = 'Shitzu',
        ['brand'] = 'Jetmax',
        ['model'] = 'jetmax',
        ['price'] = 0,
        ['category'] = 'boats',
        ['hash'] = `jetmax`,
        ['shop'] = 'boats',
    },
    ['tropic'] = {
        ['name'] = 'Shitzu',
        ['brand'] = 'Tropic',
        ['model'] = 'tropic',
        ['price'] = 0,
        ['category'] = 'boats',
        ['hash'] = `tropic`,
        ['shop'] = 'boats',
    },
    ['tropic2'] = {
        ['name'] = 'Shitzu',
        ['brand'] = 'Tropic',
        ['model'] = 'tropic2',
        ['price'] = 0,
        ['category'] = 'boats',
        ['hash'] = `tropic2`,
        ['shop'] = 'boats',
    },
    ['dinghy'] = {
        ['name'] = 'Nagasaki',
        ['brand'] = 'Dinghy',
        ['model'] = 'dinghy',
        ['price'] = 0,
        ['category'] = 'boats',
        ['hash'] = `dinghy`,
        ['shop'] = 'boats',
    },
    ['dinghy2'] = {
        ['name'] = 'Nagasaki',
        ['brand'] = 'Dinghy',
        ['model'] = 'dinghy2',
        ['price'] = 0,
        ['category'] = 'boats',
        ['hash'] = `dinghy2`,
        ['shop'] = 'boats',
    },
    ['dinghy3'] = {
        ['name'] = 'Nagasaki',
        ['brand'] = 'Dinghy',
        ['model'] = 'dinghy3',
        ['price'] = 0,
        ['category'] = 'boats',
        ['hash'] = `dinghy3`,
        ['shop'] = 'boats',
    },
    ['dinghy4'] = {
        ['name'] = 'Nagasaki',
        ['brand'] = 'Dinghy',
        ['model'] = 'dinghy4',
        ['price'] = 0,
        ['category'] = 'boats',
        ['hash'] = `dinghy4`,
        ['shop'] = 'boats',
    },
    ['suntrap'] = {
        ['name'] = 'Shitzu',
        ['brand'] = 'Suntrap',
        ['model'] = 'suntrap',
        ['price'] = 0,
        ['category'] = 'boats',
        ['hash'] = `suntrap`,
        ['shop'] = 'boats',
    },
    ['speeder'] = {
        ['name'] = 'Speeder',
        ['brand'] = 'Pegassi',
        ['model'] = 'speeder',
        ['price'] = 0,
        ['category'] = 'boats',
        ['hash'] = `speeder`,
        ['shop'] = 'boats',
    },
    ['speeder2'] = {
        ['name'] = 'Speeder',
        ['brand'] = 'Pegassi',
        ['model'] = 'speeder2',
        ['price'] = 0,
        ['category'] = 'boats',
        ['hash'] = `speeder2`,
        ['shop'] = 'boats',
    },
    ['longfin'] = {
        ['name'] = 'Longfin',
        ['brand'] = 'Shitzu',
        ['model'] = 'longfin',
        ['price'] = 0,
        ['category'] = 'boats',
        ['hash'] = `longfin`,
        ['shop'] = 'boats',
    },
    ['toro'] = {
        ['name'] = 'Toro',
        ['brand'] = 'Lampadati',
        ['model'] = 'toro',
        ['price'] = 0,
        ['category'] = 'boats',
        ['hash'] = `toro`,
        ['shop'] = 'boats',
    },
    ['toro2'] = {
        ['name'] = 'Toro',
        ['brand'] = 'Lampadati',
        ['model'] = 'toro2',
        ['price'] = 0,
        ['category'] = 'boats',
        ['hash'] = `toro2`,
        ['shop'] = 'boats',
    },
    -- helicopters
    ['buzzard2'] = {
        ['name'] = 'Buzzard',
        ['brand'] = 'Unknown',
        ['model'] = 'buzzard2',
        ['price'] = 0,
        ['category'] = 'helicopters',
        ['hash'] = `buzzard2`,
        ['shop'] = 'air',
    },
    ['frogger'] = {
        ['name'] = 'Frogger',
        ['brand'] = 'Unknown',
        ['model'] = 'frogger',
        ['price'] = 0,
        ['category'] = 'helicopters',
        ['hash'] = `frogger`,
        ['shop'] = 'air',
    },
    ['frogger2'] = {
        ['name'] = 'Frogger',
        ['brand'] = 'Unknown',
        ['model'] = 'frogger2',
        ['price'] = 0,
        ['category'] = 'helicopters',
        ['hash'] = `frogger2`,
        ['shop'] = 'air',
    },
    ['maverick'] = {
        ['name'] = 'Maverick',
        ['brand'] = 'Unknown',
        ['model'] = 'maverick',
        ['price'] = 0,
        ['category'] = 'helicopters',
        ['hash'] = `maverick`,
        ['shop'] = 'air',
    },
    ['swift'] = {
        ['name'] = 'Swift',
        ['brand'] = 'Buckingham',
        ['model'] = 'swift',
        ['price'] = 0,
        ['category'] = 'helicopters',
        ['hash'] = `swift`,
        ['shop'] = 'air',
    },
    ['swift2'] = {
        ['name'] = 'Swift',
        ['brand'] = 'Buckingham',
        ['model'] = 'swift2',
        ['price'] = 0,
        ['category'] = 'helicopters',
        ['hash'] = `swift2`,
        ['shop'] = 'air',
    },
    ['seasparrow'] = {
        ['name'] = 'Sea Sparrow',
        ['brand'] = 'Unknown',
        ['model'] = 'seasparrow',
        ['price'] = 0,
        ['category'] = 'helicopters',
        ['hash'] = `seasparrow`,
        ['shop'] = 'air',
    },
    ['seasparrow2'] = {
        ['name'] = 'Sparrow',
        ['brand'] = 'Unknown',
        ['model'] = 'seasparrow2',
        ['price'] = 0,
        ['category'] = 'helicopters',
        ['hash'] = `seasparrow2`,
        ['shop'] = 'air',
    },
    ['seasparrow3'] = {
        ['name'] = 'Sparrow',
        ['brand'] = 'Unknown',
        ['model'] = 'seasparrow3',
        ['price'] = 0,
        ['category'] = 'helicopters',
        ['hash'] = `seasparrow3`,
        ['shop'] = 'air',
    },
    ['supervolito'] = {
        ['name'] = 'SuperVolito',
        ['brand'] = 'Buckingham',
        ['model'] = 'supervolito',
        ['price'] = 0,
        ['category'] = 'helicopters',
        ['hash'] = `supervolito`,
        ['shop'] = 'air',
    },
    ['supervolito2'] = {
        ['name'] = 'SuperVolito Carbon',
        ['brand'] = 'Buckingham',
        ['model'] = 'supervolito2',
        ['price'] = 0,
        ['category'] = 'helicopters',
        ['hash'] = `supervolito2`,
        ['shop'] = 'air',
    },
    ['volatus'] = {
        ['name'] = 'Volatus',
        ['brand'] = 'Buckingham',
        ['model'] = 'volatus',
        ['price'] = 0,
        ['category'] = 'helicopters',
        ['hash'] = `volatus`,
        ['shop'] = 'air',
    },
    ['havok'] = {
        ['name'] = 'Havok',
        ['brand'] = 'Nagasaki',
        ['model'] = 'havok',
        ['price'] = 0,
        ['category'] = 'helicopters',
        ['hash'] = `havok`,
        ['shop'] = 'air',
    },
    -- Planes
    ['duster'] = {
        ['name'] = 'Duster',
        ['brand'] = 'Unknown',
        ['model'] = 'duster',
        ['price'] = 0,
        ['category'] = 'planes',
        ['hash'] = `duster`,
        ['shop'] = 'air',
    },
    ['luxor'] = {
        ['name'] = 'Luxor',
        ['brand'] = 'Buckingham',
        ['model'] = 'luxor',
        ['price'] = 0,
        ['category'] = 'planes',
        ['hash'] = `luxor`,
        ['shop'] = 'air',
    },
    ['luxor2'] = {
        ['name'] = 'Luxor Deluxe',
        ['brand'] = 'Buckingham',
        ['model'] = 'luxor2',
        ['price'] = 0,
        ['category'] = 'planes',
        ['hash'] = `luxor2`,
        ['shop'] = 'air',
    },
    ['stunt'] = {
        ['name'] = 'Mallard',
        ['brand'] = 'Unknown',
        ['model'] = 'stunt',
        ['price'] = 0,
        ['category'] = 'planes',
        ['hash'] = `stunt`,
        ['shop'] = 'air',
    },
    ['mammatus'] = {
        ['name'] = 'Mammatus',
        ['brand'] = 'Unknown',
        ['model'] = 'mammatus',
        ['price'] = 0,
        ['category'] = 'planes',
        ['hash'] = `mammatus`,
        ['shop'] = 'air',
    },
    ['velum'] = {
        ['name'] = 'Velum',
        ['brand'] = 'Unknown',
        ['model'] = 'velum',
        ['price'] = 0,
        ['category'] = 'planes',
        ['hash'] = `velum`,
        ['shop'] = 'air',
    },
    ['velum2'] = {
        ['name'] = 'Velum',
        ['brand'] = 'Unknown',
        ['model'] = 'velum2',
        ['price'] = 0,
        ['category'] = 'planes',
        ['hash'] = `velum2`,
        ['shop'] = 'air',
    },
    ['shamal'] = {
        ['name'] = 'Shamal',
        ['brand'] = 'Buckingham',
        ['model'] = 'shamal',
        ['price'] = 0,
        ['category'] = 'planes',
        ['hash'] = `shamal`,
        ['shop'] = 'air',
    },
    ['vestra'] = {
        ['name'] = 'Vestra',
        ['brand'] = 'Buckingham',
        ['model'] = 'vestra',
        ['price'] = 0,
        ['category'] = 'planes',
        ['hash'] = `vestra`,
        ['shop'] = 'air',
    },
    ['dodo'] = {
        ['name'] = 'Dodo',
        ['brand'] = 'Mammoth',
        ['model'] = 'dodo',
        ['price'] = 0,
        ['category'] = 'planes',
        ['hash'] = `dodo`,
        ['shop'] = 'air',
    },
    ['howard'] = {
        ['name'] = 'Howard NX-25',
        ['brand'] = 'Buckingham',
        ['model'] = 'howard',
        ['price'] = 0,
        ['category'] = 'planes',
        ['hash'] = `howard`,
        ['shop'] = 'air',
    },
    ['alphaz1'] = {
        ['name'] = 'Alpha-Z1',
        ['brand'] = 'Buckingham',
        ['model'] = 'alphaz1',
        ['price'] = 0,
        ['category'] = 'planes',
        ['hash'] = `alphaz1`,
        ['shop'] = 'air',
    },
    ['nimbus'] = {
        ['name'] = 'Nimbus',
        ['brand'] = 'Buckingham',
        ['model'] = 'nimbus',
        ['price'] = 0,
        ['category'] = 'planes',
        ['hash'] = `nimbus`,
        ['shop'] = 'air',
    },
    ['conada'] = {
        ['name'] = 'Conada',
        ['brand'] = 'Buckingham',
        ['model'] = 'conada',
        ['price'] = 0,
        ['category'] = 'helicopters',
        ['hash'] = `conada`,
        ['shop'] = 'air',
    },
    ['corsita'] = {
        ['name'] = 'Corsita',
        ['brand'] = 'sports',
        ['model'] = 'corsita',
        ['price'] = 0,
        ['category'] = 'sports',
        ['hash'] = `corsita`,
        ['shop'] = 'luxury',
    },
    ['draugur'] = {
        ['name'] = 'Draugur',
        ['brand'] = 'offroad',
        ['model'] = 'draugur',
        ['price'] = 0,
        ['category'] = 'offroad',
        ['hash'] = `draugur`,
        ['shop'] = 'pdm',
    },
    ['greenwood'] = {
        ['name'] = 'Greenwood',
        ['brand'] = 'muscle',
        ['model'] = 'greenwood',
        ['price'] = 0,
        ['category'] = 'muscle',
        ['hash'] = `greenwood`,
        ['shop'] = 'pdm',
    },
    ['omnisegt'] = {
        ['name'] = 'Omnis e-GT',
        ['brand'] = 'Obey',
        ['model'] = 'omnisegt',
        ['price'] = 0,
        ['category'] = 'sports',
        ['hash'] = `omnisegt`,
        ['shop'] = 'luxury',
    },

}